### ISSUE TITLE
Menüpunkt löschen

### ISSUE THREAD

**Issue by paha77** [backbone87/contao-navigation#10]
Hi,

Wie kann man mit dem "bbit_navi_item" Hook einen Menüpunkt nachträglich entfernen?

Wenn ich im Hook

```php
unset($module->arrItems[$page_id])
```
schreibe, bekomme ich (selbstverständlich) die folgende Fehlermeldung:

```Recoverable error: Argument 1 passed to AbstractModuleNavigation::compileNavigationItem() must be of the type array, null given```

weil (vermutlich) die Seite auf der vorherigen Ebene immer noch definiert ist.

Danke für die Hilfe!

**Comment by backbone87** [comment]
Wie du schon sagtest müssen noch alle Referenzen auf dieses Item entfernt werden.
Das ist leider nur möglich in dem alle Referenzen durchlaufen werden, da die Navigation nur eine Vorwärts-Referenzierung speichert (Eltern->Kind) und keine Rückwärts/Inversen-Referenzen (Kind->Eltern). `$module->arrSubitems` ist ein array aus arrays indem die Unterseiten-Referenzen gespeichert werden.
Also etwas ähnlich diesem:
```
foreach($module->arrSubitems as &$items) {
  $items = array_filter($items, function($id) use($removedID) { return $id != $removedID; });
}
unset($items);
```

Weiterhin bitte beachten, dass dies hier kein Support-System sondern ein Ticketsystem für Fehler, Verbesserungsvorschläge und Code-Contributions ist. Für Fragen zur Anwendung bitte Forum, Wiki, IRC und Mumble nutzen.
