### ISSUE TITLE
isActive flag is not set correctly

### ISSUE THREAD

**Issue by davidmaack** [backbone87/contao-navigation#8]
For some strange reasons the $GLOBALS['objPage']->id is sometimes a string. So when checking for the active id on https://github.com/backbone87/contao-navigation/blob/1.x/TL_ROOT/system/modules/backboneit_navigation/AbstractModuleNavigation.php#L341 and https://github.com/backbone87/contao-navigation/blob/1.x/TL_ROOT/system/modules/backboneit_navigation/AbstractModuleNavigation.php#L346 the result is wrong.

You would either do a type cast when setting $this->varActiveID or just test with ==

**Comment by backbone87** [comment]
das reicht nicht aus für einen fix:
varActiveID kann null/false sein falls:
- sitemap navigation oder article deeplink
- kein $GLOBALS['objPage'] (wirft zur zeit ein fehler bei https://github.com/backbone87/contao-navigation/blob/1.x/TL_ROOT/system/modules/backboneit_navigation/AbstractModuleNavigation.php#L92 das sollte aber geprüft werden)
- die ID in $GLOBALS['objPage'] nicht gesetzt ist (warum auch immer das passieren könnte)

die generelle prüfung muss also unfähr so aussehen:
`$this->varActiveID !== null && (string) $this->varActiveID === (string) $id`

wenn du ein PR erstellst, merge ich das

**Comment by frontendschlampe** [comment]
... wird hier noch irgendwas passieren? @davidmaack @backbone87 :-)

**Comment by backbone87** [comment]
inactive
