### ISSUE TITLE
Wunsch: Option "Als Sitemap anzeigen" unabhängig

### ISSUE THREAD

**Issue by Webstylerin** [backbone87/contao-navigation#9]
Hallöchen,

ich hoffe ich bin mir meiner Anfrage hier richtig, denn ich habe einen Vorschlag/Änderungswunsch für die Navigation:

Die Option "Als Sitemap anzeigen" sollte unabhängig von der Option "Versteckte Seiten anzeigen" funktionieren. Korrigiert mich bitte wenn ich das falsch verstehe, aber die Tatsache, dass die Sitemap-Einstellungen ignoriert werden wenn ich Seiten mit der Option "Im Menu verstecken" anzeigen lassen will, ergibt für mich keinen Sinn.

Mein aktueller Fall:
- Ich habe eine Standard-Contao-Navigation als Hauptnavigation die nur Seiten zeigt deren Option "im Menü verstecken" nicht aktiviert ist.
- Ich habe die Backbone-Navigation als mobile Navigation und zeige hier auch Seiten an, die im Hauptmenü versteckt sein sollen (bspw. das Impressum).
- Ich habe Seiten, die nirgends in der Navigation auftauchen sollen (bspw. "Kontaktformular gesendet"). Hier habe ich die Optionen "im Menü verstecken" und "niemals in Sitemap anzeigen" aktiviert.

Wenn jetzt die Backbone-Navigation die Sitemap-Einstellung ignoriert, nur weil die Seite im Menü versteckt ist, hab ich die unerwünschten Seiten ja dennoch in meiner mobilen Navigation, aber ich will sie nirgends haben. :)

VG
Nicole

**Comment by backbone87** [comment]
ich verstehe das problem, aber nicht wie dein vorschlag das lösen soll.

die seiteneinstellung "In der Sitemap zeigen" hat 3 zustände:
- "standard" -> übernehme die standard sichtbarkeit (d.h. abhängig von seiteneinstellung "Im Menü verstecken")
- "immer anzeigen" -> seite ist in der sitemap immer sichtbar (unabhängig von seiteneinstellung "Im Menü verstecken")
- "nie anzeigen" -> seite wird nie in der sitemap angezeigt (unabhängig von seiteneinstellung "Im Menü verstecken")

jetzt betrachten wir die 2 einstellungen aus der navi "als sitemap anzeigen" und "versteckte seiten anzeigen"

fall 1: "als sitemap anzeigen" -> nein / "versteckte seiten anzeigen" ->nein
- es werden nur seiten mit seiteneinstellung  "Im Menü verstecken" -> nein, angezeigt
- seiteneinstellung "In der Sitemap zeigen" wird ignoriert

fall 2: nein / ja
- seiteneinstellung  "Im Menü verstecken" wird ignoriert
- seiteneinstellung "In der Sitemap zeigen" wird ignoriert

fall 3: ja / nein
- alle seiten mit seiteneinstellung "In der Sitemap zeigen" -> immer anzeigen, werden auf jeden fall anzeigt
- alle seiten mit seiteneinstellung "In der Sitemap zeigen" -> nie anzeigen, werden *nicht* angezeigt
- alle seiten mit seiteneinstellung "In der Sitemap zeigen" -> standard, werden abhängig von seiteneinstellung  "Im Menü verstecken" angezeigt

fall 4: ja / ja
- alle seiten werden anzeigt außer diejenigen mit seiteneinstellung "In der Sitemap zeigen" -> nie anzeigen

**Comment by backbone87** [comment]
inactive
